//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdItemInfo
    {
        public int PlantID { get; set; }
        public int ItemID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<int> ItemUse { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> AlmariCode { get; set; }
        public string AlmariDesc { get; set; }
        public Nullable<int> RowID { get; set; }
        public Nullable<int> RacID { get; set; }
        public Nullable<int> BinID { get; set; }
        public string ItemSize { get; set; }
        public Nullable<int> ItemSource { get; set; }
        public Nullable<int> UnitCode { get; set; }
        public Nullable<int> TrackID { get; set; }
        public Nullable<int> ETrack { get; set; }
        public string Location { get; set; }
    }
}
