//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdPlant
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int PID { get; set; }
        public string PCode { get; set; }
        public string PDesc { get; set; }
        public string Active { get; set; }
    }
}
