//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sParam
    {
        public int IDCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> StartCode { get; set; }
        public string Active { get; set; }
        public Nullable<int> ParentCode { get; set; }
    }
}
